#!/usr/bin/env python3
"""Synthetic controls only: no E3 biological evidence is generated by this test."""
import copy
import importlib.util
import json
from pathlib import Path
import sys
import tempfile
import subprocess
import unittest
import numpy as np
from analysis import JointPredictor, energy_scores, cluster_summary, transform
from protocol import validate, ROOT, payload_digest
from run import evaluate, extract

class E3Tests(unittest.TestCase):
    def setUp(self):
        self.p=json.loads((ROOT/'empirical/e3/protocol.json').read_text())
        self.rng=np.random.default_rng(123)
        self.ages=np.array([70,80,90,100,110,120,180,190,200,210,220,230])
        growth=np.log(self.ages/70)
        self.y=np.column_stack([0.2+growth,1.1+growth,2+6*growth,0.1+0.1*growth,0.03+0.1*growth])
    def test_joint_draws_reproducible_and_positive_covariance(self):
        m=JointPredictor().fit(self.y,self.ages)
        a=m.draws([100,200],40,17)
        self.assertTrue(np.array_equal(a,m.draws([100,200],40,17)))
        self.assertEqual(a.shape,(40,2,5))
        self.assertTrue(np.all(np.linalg.eigvalsh(m.s)>0))
    def test_intercept_control_does_not_depend_on_test_age(self):
        m=JointPredictor(False).fit(self.y,self.ages)
        self.assertTrue(np.array_equal(m.draws([80],40,17),m.draws([220],40,17)))
    def test_score_rewards_correct_joint_distribution(self):
        draws=self.rng.normal(0,0.1,(40,3,5))
        good=energy_scores(draws,np.zeros((3,5)))
        bad=energy_scores(draws+4,np.zeros((3,5)))
        self.assertTrue(np.all(good<bad))
    def test_donor_bootstrap_not_seed_pseudoreplication(self):
        result=cluster_summary([1,1,4],['a','a','b'])
        self.assertEqual(result['donor_clusters'],2)
        self.assertEqual(result['mean_donor_weighted'],2.5)
        self.assertIsNone(result['bootstrap_95pct'])
    def test_no_imputation_or_single_age_fit(self):
        with self.assertRaises(ValueError): transform([[1,np.nan,1,.1,.1]])
        with self.assertRaises(ValueError): JointPredictor().fit(self.y,[100]*len(self.y))
    def test_protocol_draft_blocked_before_test_spikes(self):
        errors=validate(self.p)
        self.assertIn('protocol not marked registered',errors)
        self.assertTrue(any('design' in e for e in errors))
    def test_seen_data_and_donor_leakage_even_in_exploration(self):
        row={'path':'x.nwb','sha256':'a'*64,'dataset_id':'001603','organoid_id':'x',
             'culture_id':'c','donor_id':'d','lab_id':'l','preparation':'organoid','age_days':100}
        self.p['training']=[row]
        self.p['test']=[{**row,'sha256':'b'*64,'culture_id':'c2','organoid_id':'x2'}]
        errors=validate(self.p,strict=False)
        self.assertTrue(any('already seen' in e for e in errors))
        self.assertTrue(any('donor leakage' in e for e in errors))
    def test_registration_digest_changes_when_design_changes(self):
        a=payload_digest(self.p)
        self.p['registration']['url']='https://example.invalid/placeholder'
        self.assertEqual(a,payload_digest(self.p))
        self.p['analysis']['seed']+=1
        self.assertNotEqual(a,payload_digest(self.p))
    def test_invalid_protocol_types_return_errors(self):
        self.p['analysis']['min_test_donors']='five'
        self.assertTrue(validate(self.p))
    def test_runner_produces_separate_prediction_and_age_scores(self):
        result=evaluate(self.y,self.ages,self.y[:3],self.ages[:3],['a','b','c'],40,7,200)
        self.assertEqual(result['primary_difference']['donor_clusters'],3)
        self.assertEqual(len(result['models']['joint-age']['statistics']['covered_90pct']),3)
        self.assertIn('interval_width',result['models']['joint-age']['statistics'])
    def test_explicit_observation_interval_required_and_no_gap_inference(self):
        import h5py
        with tempfile.TemporaryDirectory() as d:
            path=Path(d)/'fixture.nwb'
            with h5py.File(path,'w') as f:
                u=f.create_group('units')
                u.create_dataset('spike_times',data=[1.,2.,3.])
                u.create_dataset('spike_times_index',data=[3])
            with self.assertRaisesRegex(ValueError,'obs_intervals'): extract(path)
            with h5py.File(path,'a') as f: f['units'].create_dataset('obs_intervals',data=[[0,100],[200,400]])
            with self.assertRaisesRegex(ValueError,'single observation'): extract(path)
    def test_end_to_end_exploration_is_labelled_and_cannot_overwrite(self):
        import h5py
        with tempfile.TemporaryDirectory() as directory:
            root=Path(directory)
            p=copy.deepcopy(self.p)
            p['analysis']['draws']=40
            p['analysis']['bootstrap_resamples']=100
            for split,n in [('training',6),('test',3)]:
                rows=[]
                for i in range(n):
                    name=f'{split}-{i}.nwb'; path=root/name
                    trains=[np.sort(self.rng.uniform(0,180,40+i+j)) for j in range(24)]
                    with h5py.File(path,'w') as f:
                        u=f.create_group('units')
                        u.create_dataset('spike_times',data=np.concatenate(trains))
                        u.create_dataset('spike_times_index',data=np.cumsum([len(t) for t in trains]))
                        u.create_dataset('obs_intervals',data=[[0.,180.]])
                    from protocol import digest
                    rows.append({'path':name,'sha256':digest(path),'dataset_id':'SYNTHETIC-FIXTURE-'+split,
                      'organoid_id':name,'culture_id':name,'donor_id':name,'lab_id':split,
                      'preparation':'synthetic-control-not-tissue','age_days':100 if i%2 else 200})
                p[split]=rows
            manifest=root/'manifest.json'; manifest.write_text(json.dumps(p))
            out=root/'result.json'
            command=[sys.executable,str(ROOT/'empirical/e3/run.py'),str(manifest),'--out',str(out),'--exploratory']
            done=subprocess.run(command,capture_output=True,text=True)
            self.assertEqual(done.returncode,0,done.stderr)
            result=json.loads(out.read_text())
            self.assertEqual(result['status'],'exploratory')
            self.assertFalse(result['registration_authenticated'])
            self.assertFalse(result['phenomenal_or_welfare_inference'])
            self.assertEqual(len(result['recordings']),9)
            repeat=subprocess.run(command,capture_output=True,text=True)
            self.assertNotEqual(repeat.returncode,0)
            self.assertIn('already exists',repeat.stderr)

    def test_original_evidence_remains_frozen(self):
        from protocol import digest
        lock=json.loads((ROOT/'validation/historical-evidence.json').read_text())
        for name,h in lock['files'].items(): self.assertEqual(digest(ROOT/name),h,name)

if __name__=='__main__': unittest.main(verbosity=2)
